#!/bin/sh

SINK=$(pactl list sinks short | grep RUNNING | sed -e 's,^\([0-9][0-9]*\)[^0-9].*,\1,')
case "$1" in
	m) pactl set-sink-mute $SINK toggle ;;
	d) pactl set-sink-volume $SINK -5% ;;
	i) pactl set-sink-volume $SINK +5% ;;
	*) echo $"Usage: $0 {m|d|i} (mute|dec|inc}" ; exit 1 ;;
esac
